// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpA0xdfdL8h-hdi6JcPoZIFXk1qaKQiJg',
    appId: '1:444669370263:web:877152da20f0c5c63a2ed2',
    messagingSenderId: '444669370263',
    projectId: 'daily-medicine-682d5',
    authDomain: 'daily-medicine-682d5.firebaseapp.com',
    storageBucket: 'daily-medicine-682d5.firebasestorage.app',
    measurementId: 'G-W2TRMEREEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiCKCn6boTflTI7sA8qkARD7aVGyEznMI',
    appId: '1:444669370263:android:8a3cebc8890d65a03a2ed2',
    messagingSenderId: '444669370263',
    projectId: 'daily-medicine-682d5',
    storageBucket: 'daily-medicine-682d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Y9r7VnYjVRD1d3F-eXLKzHkHmbccmJ4',
    appId: '1:444669370263:ios:c7f2e596f3758a9a3a2ed2',
    messagingSenderId: '444669370263',
    projectId: 'daily-medicine-682d5',
    storageBucket: 'daily-medicine-682d5.firebasestorage.app',
    iosBundleId: 'com.example.dailymedicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Y9r7VnYjVRD1d3F-eXLKzHkHmbccmJ4',
    appId: '1:444669370263:ios:c7f2e596f3758a9a3a2ed2',
    messagingSenderId: '444669370263',
    projectId: 'daily-medicine-682d5',
    storageBucket: 'daily-medicine-682d5.firebasestorage.app',
    iosBundleId: 'com.example.dailymedicine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpA0xdfdL8h-hdi6JcPoZIFXk1qaKQiJg',
    appId: '1:444669370263:web:dd2b64f68e3570b53a2ed2',
    messagingSenderId: '444669370263',
    projectId: 'daily-medicine-682d5',
    authDomain: 'daily-medicine-682d5.firebaseapp.com',
    storageBucket: 'daily-medicine-682d5.firebasestorage.app',
    measurementId: 'G-G52X4ZE7Y0',
  );
}
